services:
  - type: web
    name: mem0-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here